# Generated by Django 5.2.17 on 2026-09-10 11:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('RECEPCION', 'Recepción'), ('ALMACENAJE', 'Almacenaje'), ('PICKING', 'Picking'), ('DESPACHO', 'Despacho'), ('CUARENTENA', 'Cuarentena'), ('SERVICIO', 'Servicio Técnico'), ('PERSONALIZACION', 'Personalización')], max_length=20, verbose_name='Tipo de zona')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zonas', to='almacen.bodega', verbose_name='Bodega')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['bodega', 'codigo'],
                'unique_together': {('bodega', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Formato: B{num}-Z{num}-E{num}. Ej: B1-Z1-E1', max_length=50, unique=True, verbose_name='Código')),
                ('pasillo', models.CharField(blank=True, max_length=20, verbose_name='Pasillo')),
                ('rack', models.CharField(blank=True, max_length=20, verbose_name='Rack')),
                ('nivel', models.CharField(blank=True, max_length=20, verbose_name='Nivel')),
                ('posicion', models.CharField(blank=True, max_length=20, verbose_name='Posición')),
                ('capacidad_maxima', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad máxima (unidades)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones', to='almacen.zona', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='almacen_ubi_codigo_5a8645_idx')],
            },
        ),
    ]
