# Generated by Django 5.2.17 on 2026-09-15 16:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
        ('catalogo', '0003_producto_clasificacion_abc_producto_codigo_barras_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('RETIRO', 'Retiro'), ('TRASLADO', 'Traslado')], max_length=20, verbose_name='Tipo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
            ],
            options={
                'verbose_name': 'Movimiento de ubicación',
                'verbose_name_plural': 'Movimientos de ubicación',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='coordenada_x',
            field=models.IntegerField(default=0, verbose_name='Coordenada X'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='coordenada_y',
            field=models.IntegerField(default=0, verbose_name='Coordenada Y'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='peso_maximo_kg',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso máximo (kg)'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='tipo_ubicacion',
            field=models.CharField(choices=[('ESTANTE', 'Estante'), ('PISO', 'Piso'), ('REFRIGERADO', 'Refrigerado'), ('CUARENTENA', 'Cuarentena')], default='ESTANTE', max_length=20, verbose_name='Tipo de ubicación'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='volumen_m3',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Volumen (m³)'),
        ),
        migrations.AddIndex(
            model_name='ubicacion',
            index=models.Index(fields=['zona', 'activo'], name='almacen_ubi_zona_id_258987_idx'),
        ),
        migrations.AddField(
            model_name='movimientoubicacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_ubicacion', to='catalogo.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='movimientoubicacion',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_ubicacion', to='almacen.ubicacion', verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='movimientoubicacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_ubicacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
