# Generated by Django 5.2.17 on 2026-09-10 11:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('cantidad_reservada', models.IntegerField(default=0, help_text='Unidades comprometidas en pedidos pendientes', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad reservada')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias', to='catalogo.producto', verbose_name='Producto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias', to='almacen.ubicacion', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Existencia',
                'verbose_name_plural': 'Existencias',
                'ordering': ['producto', 'ubicacion'],
                'indexes': [models.Index(fields=['producto', 'ubicacion'], name='inventario__product_727e02_idx')],
                'unique_together': {('producto', 'ubicacion')},
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('TRASLADO', 'Traslado'), ('AJUSTE_POS', 'Ajuste positivo'), ('AJUSTE_NEG', 'Ajuste negativo'), ('DEVOLUCION', 'Devolución'), ('SERVICIO', 'Envío a servicio técnico'), ('PERSONALIZACION', 'Envío a personalización')], max_length=20, verbose_name='Tipo de movimiento')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('documento', models.CharField(blank=True, help_text='N° de orden, factura, guía, etc.', max_length=100, verbose_name='Documento de referencia')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('fecha_movimiento', models.DateField(blank=True, help_text='Fecha real del movimiento (puede diferir de la fecha de registro)', null=True, verbose_name='Fecha del movimiento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='catalogo.producto', verbose_name='Producto')),
                ('ubicacion_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_entrada', to='almacen.ubicacion', verbose_name='Ubicación destino')),
                ('ubicacion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_salida', to='almacen.ubicacion', verbose_name='Ubicación origen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos (Kardex)',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='inventario__fecha_485921_idx'), models.Index(fields=['producto', '-fecha'], name='inventario__product_676862_idx'), models.Index(fields=['tipo'], name='inventario__tipo_85c477_idx')],
            },
        ),
    ]
