# Generated by Django 5.2.17 on 2026-09-15 17:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0002_movimientoubicacion_ubicacion_coordenada_x_and_more'),
        ('catalogo', '0003_producto_clasificacion_abc_producto_codigo_barras_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Ej: OC-2026-001', max_length=20, unique=True, verbose_name='Número de orden')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('fecha_esperada', models.DateField(verbose_name='Fecha esperada de entrega')),
                ('fecha_recepcion', models.DateField(blank=True, null=True, verbose_name='Fecha de recepción')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('documento_referencia', models.CharField(blank=True, help_text='Factura, guía de remisión, etc.', max_length=100, verbose_name='Documento de referencia')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_recepcion', to='catalogo.proveedor', verbose_name='Proveedor')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('usuario_recepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que recibió')),
            ],
            options={
                'verbose_name': 'Orden de recepción',
                'verbose_name_plural': 'Órdenes de recepción',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LineaRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_esperada', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad esperada')),
                ('cantidad_recibida', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad recibida')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de recepción')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_recepcion', to='catalogo.producto', verbose_name='Producto')),
                ('ubicacion_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='almacen.ubicacion', verbose_name='Ubicación destino')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='recepcion.ordenrecepcion', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Línea de recepción',
                'verbose_name_plural': 'Líneas de recepción',
                'ordering': ['orden', 'producto'],
                'unique_together': {('orden', 'producto')},
            },
        ),
    ]
