# Generated by Django 5.2.17 on 2026-09-15 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_proveedor_unidadmedida_producto_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='clasificacion_abc',
            field=models.CharField(choices=[('A', 'A - Alta rotación'), ('B', 'B - Media rotación'), ('C', 'C - Baja rotación')], default='C', max_length=1, verbose_name='Clasificación ABC'),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, db_index=True, help_text='EAN-13, UPC, etc.', max_length=50, verbose_name='Código de barras'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso (kg)'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo_barras'], name='catalogo_pr_codigo__7bf292_idx'),
        ),
    ]
