# Generated by Django 5.2.17 on 2026-09-15 17:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0002_movimientoubicacion_ubicacion_coordenada_x_and_more'),
        ('catalogo', '0003_producto_clasificacion_abc_producto_codigo_barras_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CED', 'Cédula'), ('RUC', 'RUC'), ('PAS', 'Pasaporte')], default='CED', max_length=3, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='Número de documento')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón social')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Ej: PED-2026-001', max_length=20, unique=True, verbose_name='Número de pedido')),
                ('fecha_pedido', models.DateField(auto_now_add=True, verbose_name='Fecha de pedido')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de entrega estimada')),
                ('fecha_despacho', models.DateField(blank=True, null=True, verbose_name='Fecha de despacho')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PICKING', 'En picking'), ('PREPARADO', 'Preparado'), ('DESPACHADO', 'Despachado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('direccion_entrega', models.CharField(blank=True, max_length=300, verbose_name='Dirección de entrega')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='despacho.cliente', verbose_name='Cliente')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('usuario_despacho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_despachados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que despachó')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('cantidad_preparada', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad preparada')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio unitario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_pedido', to='catalogo.producto', verbose_name='Producto')),
                ('ubicacion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='almacen.ubicacion', verbose_name='Ubicación origen')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='despacho.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Línea de pedido',
                'verbose_name_plural': 'Líneas de pedido',
                'ordering': ['pedido', 'producto'],
                'unique_together': {('pedido', 'producto')},
            },
        ),
    ]
