# Generated by Django 5.2.17 on 2026-09-16 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadReciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('VER', 'Ver'), ('PROCESAR', 'Procesar')], max_length=10, verbose_name='Acción')),
                ('modulo', models.CharField(choices=[('CATALOGO', 'Catálogo'), ('ALMACEN', 'Almacén'), ('INVENTARIO', 'Inventario'), ('RECEPCION', 'Recepción'), ('DESPACHO', 'Despacho'), ('SERVICIO', 'Servicio')], max_length=20, verbose_name='Módulo')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='URL')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad reciente',
                'verbose_name_plural': 'Actividades recientes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('REUNION', 'Reunión'), ('ENTREGA', 'Entrega'), ('RECEPCION', 'Recepción programada'), ('SERVICIO', 'Servicio técnico'), ('PERSONAL', 'Personal'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Tipo')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha de fin')),
                ('todo_el_dia', models.BooleanField(default=False, verbose_name='Todo el día')),
                ('ubicacion', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VENTAS', 'Ventas'), ('REPARACIONES', 'Reparaciones'), ('RECEPCIONES', 'Recepciones'), ('CLIENTES', 'Clientes atendidos'), ('CUSTOM', 'Personalizada')], default='CUSTOM', max_length=20, verbose_name='Tipo')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('objetivo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Objetivo')),
                ('progreso', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Progreso')),
                ('periodo', models.CharField(choices=[('DIARIA', 'Diaria'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual'), ('ANUAL', 'Anual')], default='MENSUAL', max_length=15, verbose_name='Período')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('completada', models.BooleanField(default=False, verbose_name='Completada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['-activa', 'fecha_fin'],
            },
        ),
        migrations.CreateModel(
            name='NotaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('color', models.CharField(choices=[('AMARILLO', 'Amarillo'), ('VERDE', 'Verde'), ('AZUL', 'Azul'), ('ROJO', 'Rojo'), ('MORADO', 'Morado')], default='AMARILLO', max_length=10, verbose_name='Color')),
                ('fijada', models.BooleanField(default=False, verbose_name='Fijada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota rápida',
                'verbose_name_plural': 'Notas rápidas',
                'ordering': ['-fijada', '-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INFO', 'Información'), ('SUCCESS', 'Éxito'), ('WARNING', 'Advertencia'), ('URGENT', 'Urgente')], default='INFO', max_length=10, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('url_destino', models.CharField(blank=True, max_length=500, verbose_name='URL destino')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PreferenciaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(choices=[('OSCURO', 'Oscuro'), ('CLARO', 'Claro')], default='OSCURO', max_length=10, verbose_name='Tema')),
                ('notif_email', models.BooleanField(default=True, verbose_name='Notificaciones por email')),
                ('notif_dashboard', models.BooleanField(default=True, verbose_name='Notificaciones en dashboard')),
                ('mostrar_calendario', models.BooleanField(default=True, verbose_name='Mostrar calendario')),
                ('mostrar_tareas', models.BooleanField(default=True, verbose_name='Mostrar tareas')),
                ('mostrar_metas', models.BooleanField(default=True, verbose_name='Mostrar metas')),
                ('mostrar_notas', models.BooleanField(default=True, verbose_name='Mostrar notas')),
                ('mostrar_kpis', models.BooleanField(default=True, verbose_name='Mostrar KPIs')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia',
                'verbose_name_plural': 'Preferencias',
            },
        ),
        migrations.CreateModel(
            name='TareaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('GENERAL', 'General'), ('RECEPCION', 'Recepción'), ('DESPACHO', 'Despacho'), ('INVENTARIO', 'Inventario'), ('SERVICIO', 'Servicio Técnico')], default='GENERAL', max_length=20, verbose_name='Categoría')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('fecha_limite', models.DateTimeField(blank=True, null=True, verbose_name='Fecha límite')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_completada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea personal',
                'verbose_name_plural': 'Tareas personales',
                'ordering': ['estado', '-prioridad', 'fecha_limite'],
            },
        ),
    ]
