# Generated by Django 5.2.17 on 2026-09-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, help_text='Ej: Jefe de Bodega, Técnico, Vendedor', max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('JEFE', 'Jefe'), ('OPERARIO', 'Operario'), ('CONSULTA', 'Consulta')], default='CONSULTA', max_length=20, verbose_name='Rol en el sistema'),
        ),
    ]
